server:
  port: 8088
  
spring:
  data:
    mongodb:
      authenticationDatabase: demo
      host: 127.0.0.2
      port: 27017
      username: Usuario1
      password: Pass1234
      database: demo
logging:
  level:
    root: DEBUG
