server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8082/eureka/
spring:
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        password: Admin100
        url: jdbc:sqlserver://localhost;databaseName=DocumentosWeb
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
