#Application Name
spring:
  application:
    name: eureka-server

server:
  port: 8082

eureka:
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
